### PR TITLE
Fix browser polyfill for Babel 7

### LINKED ISSUE #161: Polyfill missing in output due to bad path handling
In the lines quoted here, the plugin constructs a path to `@babel/core` in order to fetch the browser polyfill into the broccoli pipeline:

https://github.com/babel/broccoli-babel-transpiler/blob/7c4a3349ff3aaa32690324814e53b0dce1343bfe/index.js#L64-L65

On one of my development systems, this fails because npm installs `@babel/core` into `./node_modules/@babel/core`; as a result, the path returned by `require.resolve()` no longer matches `/\/babel-core\/.*$/` -- and my other development system is a Windows 10 machine, where `require.resolve()` returns a path separated with backslashes.

### PR DESCRIPTION
**Pull request by Elberet**
The Babel polyfill is no longer provided in the @babel/core package but was moved to @babel/polyfill. This updates the plugin to:
* add `@babel/polyfill` as a dependency,
* grab the browser polyfill script from the new package in a platform-agnostic fashion,
* allow the consumer to configure the filename of the polyfill script in the output tree.

Fixes #161

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -60,17 +75,6 @@ function Babel(inputTree, _options) {
...
-    var babelCorePath = require.resolve('@babel/core');
-    babelCorePath = babelCorePath.replace(/\/babel-core\/.*$/, '/babel-core');
-
-    let polyfill = funnel(babelCorePath, { files: ['browser-polyfill.js'] });
-    this.inputTree = mergeTrees([polyfill, inputTree]);
-  } else {
-    this.inputTree = inputTree;
-  }
-  delete this.options.browserPolyfill;
-
```
Comment (Turbo87) [inline index.js]: was there a particular reason for moving the block above the `Filter.call()`?

Comment (Elberet) [reply index.js]: Yeah, the code is building a modified input tree which must be passed into the super class' constructor. Modifying `this.inputTree` after calling the constructor doesn't work (anymore?).

File: package.json [hunk 2]
```diff
@@ -37,6 +37,7 @@
   "homepage": "https://github.com/babel/broccoli-babel-transpiler",
   "dependencies": {
     "@babel/core": "^7.0.0",
+    "@babel/polyfill": "^7.0.0",
```
Comment (rwjblue) [inline package.json]: Should we bump/set the minimum versions of both @babel packages here? Seems fine for a follow-up PR, just a thought I had as reviewing...

Comment (Elberet) [reply package.json]: Would bumping the version to, e.g. `^7.2.0` have any detrimental effects? If not I'd just go for it.
